### ISSUE TITLE
Missing OpenStreetMap attribution

### ISSUE THREAD

**Issue by habi** [gperonato/velorouter#1]
As an avid OpenStreetMap contributor and cyclist, I am pleased to see that you are using OpenStreetMap as a background layer on https://velorouter.ch

However, I noticed that the map seems to lack the proper credit.
OpenStreetMap's license requires that you both credit OpenStreetMap and make users aware of the data license (by linking to our copyright page). For more information, see: https://www.openstreetmap.org/copyright

The correct attribution helps to avoid misunderstandings about the source of the map or data, as well as what others are allowed to do with it. If you need help making the changes or have further questions,
feel free to ask in one of OpenStreetMap's communication channels: https://wiki.openstreetmap.org/wiki/Contact

More importantly attribution helps us spread the word about
OpenStreetMap and attract new contributors and build the community.
This is incredibly important to improving the quality of the database that you and millions of others rely on.

**Comment by gperonato** [comment]
Hi David,
Thank you for pointing this out. I appreciate a lot the work of all OpenStreetMap contributors and I am sorry I forgot to give proper credit. I have added the attribution now. Please let me know if this not done properly.
Thank you again!
Giuseppe

**Comment by habi** [comment]
> I have added the attribution now. Please let me know if this not done properly.

Looks good, thanks for the quick fix!
